name: Website

on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git config --global user.email aallysson0@gmail.com
          git config --global user.name Allysson Santos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: deploy
        run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          GIT_AUTHOR_NAME: Allysson Santos
          GIT_AUTHOR_EMAIL: aallysson0@gmail.com
          GIT_COMMITTER_NAME: Allysson Santos
          GIT_COMMITTER_EMAIL: aallysson0@gmail.com
