name: Gatsby

on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure CI Git User
        run: |
          git remote set-url origin https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout master
          git config --global user.email aallysson0@gmail.com
          git config --global user.name Allysson Santos
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: test
        run: yarn test

      - name: deploy
        run: yarn semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
          GATSBY_API_KEY: ${{ secrets.GATSBY_API_KEY }}
          GATSBY_AUTH_DOMAIN: ${{ secrets.GATSBY_AUTH_DOMAIN }}
          GATSBY_PROJECT_ID: ${{ secrets.GATSBY_PROJECT_ID }}
          GATSBY_STORAGE_BUCKET: ${{ secrets.GATSBY_STORAGE_BUCKET }}
          GATSBY_MESSAGING_SENDER_ID: ${{ secrets.GATSBY_MESSAGING_SENDER_ID }}
          GATSBY_APP_ID: ${{ secrets.GATSBY_APP_ID }}
          GATSBY_MEASUREMENT_ID: ${{ secrets.GATSBY_MEASUREMENT_ID }}
          GATSBY_MIXPANEL_TOKEN: ${{ secrets.GATSBY_MIXPANEL_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
